# This module finds an installed Vigra package.
#
# It sets the following variables:
#  INFERNO_EXTERNALS_FOUND              
#          
#  INFERNO_EXTERNALS_LIBRARY_DIR


FIND_PATH(INFERNO_EXTERNALS_INCLUDE_DIR NAMES /inferno/externals/qpbo/QPBO.h)
#FIND_LIBRARY(INFERNO_EXTERNALS_IMPEX_LIBRARY vigraimpex PATHS $ENV{INFERNO_EXTERNALS_ROOT}/src/impex $ENV{INFERNO_EXTERNALS_ROOT}/lib ENV LD_LIBRARY_PATH ENV LIBRARY_PATH)




#IF (INFERNO_EXTERNALS_INCLUDE_DIR)
#SET(INFERNO_EXTERNALS_FOUND TRUE)
#ENDIF (INFERNO_EXTERNALS_INCLUDE_DIR)
#
#IF (INFERNO_EXTERNALS_FOUND)
#	IF (NOT INFERNO_EXTERNALS_FIND_QUIETLY)
#		MESSAGE(STATUS "Found INFERNO_EXTERNALS_INCLUDE_DIR: ${INFERNO_EXTERNALS_INCLUDE_DIR}")
#	ENDIF (NOT INFERNO_EXTERNALS_FIND_QUIETLY)
#ELSE (INFERNO_EXTERNALS_FOUND)
#	IF (INFERNO_EXTERNALS_FIND_REQUIRED)
#		MESSAGE(FATAL_ERROR "Could not find INFERNO_EXTERNALS_INCLUDE_DIR")
#	ENDIF (INFERNO_EXTERNALS_FIND_REQUIRED)
#ENDIF (INFERNO_EXTERNALS_FOUND)


# handle the QUIETLY and REQUIRED arguments and set INFERNO_EXTERNALS_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(INFERNO_EXTERNALS DEFAULT_MSG  INFERNO_EXTERNALS_INCLUDE_DIR )

MARK_AS_ADVANCED( INFERNO_EXTERNALS_INCLUDE_DIR )
