



FIND_PATH(INFERNO_EXTERNALS_INCLUDE_DIR NAMES inferno_externals_path.hxx)
FIND_PATH(INFERNO_EXTERNALS_LIBRARIES_DIR NAMES inferno-qpbo-shared)

FIND_LIBRARY(INFERNO_EXTERNAL_LIB_QPBO_SHARED inferno-external-qpbo-shared PATHS ${INFERNO_EXTERNALS_LIBRARIES_DIR})
FIND_LIBRARY(INFERNO_EXTERNAL_LIB_TRWS_SHARED inferno-external-trws-shared PATHS ${INFERNO_EXTERNALS_LIBRARIES_DIR})




#IF (INFERNO_EXTERNALS_INCLUDE_DIR)
#SET(INFERNO_EXTERNALS_FOUND TRUE)
#ENDIF (INFERNO_EXTERNALS_INCLUDE_DIR)
#
#IF (INFERNO_EXTERNALS_FOUND)
#	IF (NOT INFERNO_EXTERNALS_FIND_QUIETLY)
#		MESSAGE(STATUS "Found INFERNO_EXTERNALS_INCLUDE_DIR: ${INFERNO_EXTERNALS_INCLUDE_DIR}")
#	ENDIF (NOT INFERNO_EXTERNALS_FIND_QUIETLY)
#ELSE (INFERNO_EXTERNALS_FOUND)
#	IF (INFERNO_EXTERNALS_FIND_REQUIRED)
#		MESSAGE(FATAL_ERROR "Could not find INFERNO_EXTERNALS_INCLUDE_DIR")
#	ENDIF (INFERNO_EXTERNALS_FIND_REQUIRED)
#ENDIF (INFERNO_EXTERNALS_FOUND)


# handle the QUIETLY and REQUIRED arguments and set INFERNO_EXTERNALS_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(INFERNO_EXTERNALS DEFAULT_MSG  INFERNO_EXTERNALS_INCLUDE_DIR  INFERNO_EXTERNALS_LIBRARIES_DIR)

MARK_AS_ADVANCED( INFERNO_EXTERNALS_INCLUDE_DIR INFERNO_EXTERNALS_LIBRARIES_DIR)
