



FIND_PATH(INFERNO_EXTERNALS_INCLUDE_DIR NAMES inferno_externals_path.hxx)
FIND_PATH(INFERNO_EXTERNALS_LIBRARIES_DIR NAMES inferno-external-qpbo-shared)

SET(TO_FIND "")

IF(WITH_QPBO)
    FIND_LIBRARY(INFERNO_EXTERNAL_LIB_QPBO_SHARED 
        NAMES inferno-external-qpbo-shared libinferno-external-qpbo-shared 
        PATHS ${INFERNO_EXTERNALS_LIBRARIES_DIR})
    SET(TO_FIND ${TO_FIND} INFERNO_EXTERNAL_LIB_QPBO_SHARED)
ENDIF(WITH_QPBO)

IF(WITH_TRWS)
    FIND_LIBRARY(INFERNO_EXTERNAL_LIB_TRWS_SHARED 
        NAMES inferno-external-trws-shared libinferno-external-trws-shared 
        PATHS ${INFERNO_EXTERNALS_LIBRARIES_DIR})
    SET(TO_FIND ${TO_FIND} INFERNO_EXTERNAL_LIB_TRWS_SHARED)
ENDIF(WITH_TRWS)



#IF (INFERNO_EXTERNALS_INCLUDE_DIR)
#SET(INFERNO_EXTERNALS_FOUND TRUE)
#ENDIF (INFERNO_EXTERNALS_INCLUDE_DIR)
#IF (INFERNO_EXTERNALS_FOUND)
#	IF (NOT INFERNO_EXTERNALS_FIND_QUIETLY)
#		MESSAGE(STATUS "Found INFERNO_EXTERNALS_INCLUDE_DIR: ${INFERNO_EXTERNALS_INCLUDE_DIR}")
#	ENDIF (NOT INFERNO_EXTERNALS_FIND_QUIETLY)
#ELSE (INFERNO_EXTERNALS_FOUND)
#	IF (INFERNO_EXTERNALS_FIND_REQUIRED)
#		MESSAGE(FATAL_ERROR "Could not find INFERNO_EXTERNALS_INCLUDE_DIR")
#	ENDIF (INFERNO_EXTERNALS_FIND_REQUIRED)
#ENDIF (INFERNO_EXTERNALS_FOUND)


# handle the QUIETLY and REQUIRED arguments and set INFERNO_EXTERNALS_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(INFERNO_EXTERNALS DEFAULT_MSG  INFERNO_EXTERNALS_INCLUDE_DIR  INFERNO_EXTERNALS_LIBRARIES_DIR ${TO_FIND})

MARK_AS_ADVANCED( INFERNO_EXTERNALS_INCLUDE_DIR INFERNO_EXTERNALS_LIBRARIES_DIR ${TO_FIND})
